# Generated by Django 3.2.5 on 2022-06-26 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
